[package]
name = "pump_steamm"
version = "0.0.1"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }

# For remote import, use the `{ git = "...", subdir = "...", rev = "..." }`.
# Revision can be a branch, a tag, and a commit hash.
# MyRemotePackage = { git = "https://some.remote/host.git", subdir = "remote/path", rev = "main" }

# For local dependencies use `local = path`. Path is relative to the package root
# Local = { local = "../path/to" }

# To resolve a version conflict and force a specific version for dependency
# override use `override = true`
# Override = { local = "../conflicting/version", override = true }

[addresses]
# NOTE: After successful update, replace these with the new addresses
# pump_steamm = "0x0" # Used for deployment
pump_steamm = "0x9147edc49978f716a6fd00b14ae467c4035a78ca660503c2e3f18bc0b618d046"
# pump_steamm = "0x3a15808b704196e34b2b651730982abcce673cd8d844692657968cec93900b91"
# pump_steamm = "0x41188de5dcc9efc58d2f1153f0bf2388e8728a70af3200c23fe3d76e3d0d39d5"
# pump_steamm = "0x283667f0bb84cbbb618e2e3ec47b60a01274d61e35769ac57a896d08fd2a51c2"
# pump_steamm = "0x68d75035a5a1d4298a6324342e47c467353e4c53dab65e15026ea95766e39570"
# pump_steamm = "0x2530e02021b36fe37df207c1abee7f50870133fd6ea9c5e8bf596f8fe2f6f31b"
# pump_steamm = "0xe5a379be247cfb0310a1292fb00cd662c3d775a1bcde2977235b0d209be5dac7"
# global_admin = "0xb6fe05877e3b7f4f81e4cd9c56cfbb784dcc5078542e2d8442c46208b1ab8980"
# registry = "0x9cafa78b96898812335b9cae0b6ebea588457254c6ca42c484639059e00fe1bc"
# upgrade_cap = "0x81d165d8ff3d8962282b790a612852f433376c44886272e2e1e57aac15833291"

# Named addresses will be accessible in Move as `@name`. They're also exported:
# for example, `std = "0x1"` is exported by the Standard Library.
# alice = "0xA11CE"

[dev-dependencies]
# The dev-dependencies section allows overriding dependencies for `--test` and
# `--dev` modes. You can introduce test-only dependencies here.
# Local = { local = "../path/to/dev-build" }

[dev-addresses]
# The dev-addresses section allows overwriting named addresses for the `--test`
# and `--dev` modes.
# alice = "0xB0B"

